### PR TITLE
Fix inspector addTree ignoring options

### PR DESCRIPTION
**Pull request by merwaaan**
addTree used an options.tree_options variable which does not exist in the codebase, instead of the passed options object.

### CODE REVIEW

**Comment by merwaaan** [comment]
Have you considered this pull request @jagenjo ?

**Comment by jagenjo** [comment]
oh, I never saw it. sorry, accepting it

**Comment by merwaaan** [comment]
Thanks!

**Comment by merwaaan** [comment]
(it seems you closed it though :) @jagenjo )

**Pull request closed without merging**
